# Generated by Django 4.2.9 on 2024-07-06 13:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfig',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='distance_additional_price',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='distance_base_kms',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='distance_base_price',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='initial_waiting_time',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='time_multiplier_factor',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='waiting_charges',
        ),
        migrations.RemoveField(
            model_name='pricingconfiglog',
            name='change_description',
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='config_name',
            field=models.CharField(default=datetime.datetime(2024, 7, 6, 13, 12, 37, 31694, tzinfo=datetime.timezone.utc), max_length=50),
        ),
        migrations.AddField(
            model_name='pricingconfiglog',
            name='new_value',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pricingconfiglog',
            name='old_value',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pricingconfiglog',
            name='changed_by',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='DayPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('distance_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_base_kms', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_additional_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_multiplier_factor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('waiting_charges', models.DecimalField(decimal_places=2, max_digits=5)),
                ('initial_waiting_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pricing_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_configs', to='pricing.pricingconfig')),
            ],
        ),
    ]
