# Generated by Django 4.2.9 on 2024-07-06 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_remove_pricingconfig_days_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='config_name',
            field=models.CharField(default=datetime.datetime(2024, 7, 6, 13, 12, 40, 827169, tzinfo=datetime.timezone.utc), max_length=50),
        ),
    ]
