# Generated by Django 4.2.9 on 2024-07-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_pricingconfig_config_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='config_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
